# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5116

# Company APIS
## POST /api/Companies
## GET /api/Companies
## GET /api/Companies/{companyID}
## GET /api/Companies?pageSize=2&pageIndex=3
## PUT /api/Companies/{companyID}
# Employee APIS
## POST /api/Companies/{companyID}/Employees
## GET /api/Companies/{companyID}/Employees
## GET /api/Companies/{companyID}/Employees/{employeeId}
## PUT /api/Companies/{companyID}/Employees/{employeeId}
## DELETE /api/Companies/{companyID}/Employees/{employeeId}


### Add a Company
POST http://localhost:5116/api/companies
Content-Type: application/json
 
{
  "name": "New Company"
}

### Get All Companies
GET http://localhost:5116/api/companies

### Get Specific Company
GET http://localhost:5116/api/companies/{companyId}

### Get Companies with Pagination
GET http://localhost:5116/api/companies?pageIndex=1&pageSize=5

### Update Company Information
PUT http://localhost:5116/api/companies/{companyId}
Content-Type: application/json
 
{
  "name": "Updated Company Name"
}

### Add an Employee to a Company
POST http://localhost:5116/api/companies/{companyId}/employees
Content-Type: application/json
 
{
  "name": "New Employee",
  "salary": 50000
}

### Delete a Specific Employee
DELETE http://localhost:5116/api/companies/{companyId}/employees/{employeeId}

### Get All Employees of a Company
GET http://localhost:5116/api/companies/{companyId}/employees

### Update Employee Information
PUT http://localhost:5116/api/companies/{companyId}/employees/{employeeId}
Content-Type: application/json
 
{
  "name": "Updated Employee Name",
  "salary": 55000
}
 
### Delete a Company and Its Employees
DELETE http://localhost:5116/api/companies/{companyId}
